# ansible/roles/prometheus/templates/prometheus.yml
# A scrape configuration containing endpoints to scrape:

global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.16.128.14:9090']

  - job_name: 'webserver'
    static_configs:
      - targets: ['172.16.128.11:9100']

  - job_name: 'databaseserver'
    static_configs:
      - targets: ['172.16.128.13:9100']

  - job_name: 'jenkinsserver'
    static_configs:
      - targets: ['172.16.128.12:9100']
